### ISSUE TITLE
Fails to apply a plan with aws_sqs_queue_policy defined

### ISSUE THREAD

**Issue by jce-redhat** [ansible-collections/cloud.terraform#86]
##### SUMMARY

I have a terraform plan that defines an `aws_sqs_queue_policy` resource.  Using the cloud.terraform.terraform module to apply the plan fails with a Python exception.  If I comment out or remove the `aws_sqs_queue_policy` resource, applying the plan succeeds as expected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`cloud.terraform.terraform` module

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.14.4]
  config file = /home/localadmin/dev/reproduce-ansible-terraform-error/ansible.cfg
  configured module search path = ['/home/localadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/localadmin/dev/reproduce-ansible-terraform-error/collections
  executable location = /usr/bin/ansible
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list cloud.terraform

# /home/localadmin/dev/reproduce-ansible-terraform-error/collections/ansible_collections
Collection      Version
--------------- -------
cloud.terraform 1.1.1
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/home/user/dev/reproduce-ansible-terraform-error/ansible.cfg) = ['/home/user/dev/reproduce-ansible-terraform-error/collections']
CONFIG_FILE() = /home/user/dev/reproduce-ansible-terraform-error/ansible.cfg
```

##### OS / ENVIRONMENT

OS is RHEL 9.1

```
$ terraform --version
Terraform v1.4.2
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.5.4. You can update by downloading from https://www.terraform.io/downloads.html
```

##### STEPS TO REPRODUCE

I'm using the following main.tf:

```
provider "aws" {
  region = "us-east-2"
}

resource "aws_sqs_queue" "this" {
  name = "reproducer-queue"
}

data "aws_iam_policy_document" "this" {
  statement {
    effect = "Allow"

    principals {
      type = "AWS"
      identifiers = [
        aws_iam_role.this.arn
      ]
    }

    actions = [
      "sqs:SendMessage"
    ]

    resources = [
      aws_sqs_queue.this.arn
    ]
  }
}

resource "aws_sqs_queue_policy" "this" {
  queue_url = aws_sqs_queue.this.id
  policy    = data.aws_iam_policy_document.this.json
}

resource "aws_iam_role" "this" {
  name = "eda_forwarder_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Sid    = ""
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "this" {
  role       = aws_iam_role.this.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}
```

This playbook is used to apply the terraform plan:

```yaml
---
- name: Reproduce cloud.terraform apply error
  hosts: localhost

  tasks:
    - name: Apply terraform AAP infrastructure plan
      cloud.terraform.terraform:
        project_path: '{{ playbook_dir }}/build'
        state: present
        force_init: true

...
```

##### EXPECTED RESULTS

Playbook should succeed and all defined terraform resources should be created.

##### ACTUAL RESULTS

```paste below
$ ansible-playbook apply.yml -vvv
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
ansible-playbook [core 2.14.4]
  config file = /home/user/dev/reproduce-ansible-terraform-error/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/dev/reproduce-ansible-terraform-error/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/user/dev/reproduce-ansible-terraform-error/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: apply.yml ************************************************************
1 plays in apply.yml

PLAY [Reproduce cloud.terraform apply error] ***********************************

TASK [Gathering Facts] *********************************************************
task path: /home/user/dev/reproduce-ansible-terraform-error/apply.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user
<127.0.0.1> EXEC /bin/sh -c 'echo ~user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1690921267.7795496-12710-197576117
063153 `" && echo ansible-tmp-1690921267.7795496-12710-197576117063153="` echo /home/user/.ansible/tmp/ansible-tmp-1690921267.7795496-12710-197576117063153 `" ) && sleep 0'
Using module file /usr/lib/python3.9/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/user/.ansible/tmp/ansible-local-12705g5zbt519/tmp0pmn7il9 TO /home/user/.ansible/tmp/ansible-tmp-1690921267.7795496-12710-197576117063153/AnsiballZ_set
up.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1690921267.7795496-12710-197576117063153/ /home/user/.ansible/tmp/ansible-tmp-1690921267.7795496-1
2710-197576117063153/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-1690921267.7795496-12710-197576117063153/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1690921267.7795496-12710-197576117063153/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [Apply terraform AAP infrastructure plan] *********************************                                                                                    [34/1417]
task path: /home/user/dev/reproduce-ansible-terraform-error/apply.yml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user
<127.0.0.1> EXEC /bin/sh -c 'echo ~user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-16757231678
8460 `" && echo ansible-tmp-1690921268.38882-12787-167572316788460="` echo /home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460 `" ) && sleep 0'
Using module file /home/user/dev/reproduce-ansible-terraform-error/collections/ansible_collections/cloud/terraform/plugins/modules/terraform.py
<127.0.0.1> PUT /home/user/.ansible/tmp/ansible-local-12705g5zbt519/tmp8q5xr8cn TO /home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/AnsiballZ_terra
form.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/ /home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787
-167572316788460/AnsiballZ_terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/AnsiballZ_terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/AnsiballZ_terraform.py", line 107, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/AnsiballZ_terraform.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/AnsiballZ_terraform.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cloud.terraform.plugins.modules.terraform', init_globals=dict(_module_fqn='ansible_collections.cloud.terraform.plugins.mod
ules.terraform', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/modules/terraform.p
y", line 659, in <module>
  File "/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/modules/terraform.p
y", line 591, in main
  File "/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/terraf
orm_commands.py", line 215, in show
  File "/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/models
.py", line 108, in from_json
  File "/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/models
.py", line 93, in from_json
  File "/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/models
.py", line 78, in from_json
  File "/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/models
.py", line 78, in <listcomp>
  File "/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/models
.py", line 49, in from_json
KeyError: 'values'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/AnsiballZ_terraform.py\", line
107, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/AnsiballZ_terraform.py\", line 99, in _ansiballz
_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1690921268.38882-12787-167572316788460/AnsiballZ_terraform.py
\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cloud.terraform.plugins.modules.terraform', init_globals=dict(_module_fqn='ansible_collecti
ons.cloud.terraform.plugins.modules.terraform', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(co
de, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/
lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terr
aform_payload.zip/ansible_collections/cloud/terraform/plugins/modules/terraform.py\", line 659, in <module>\n  File \"/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0
/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/modules/terraform.py\", line 591, in main\n  File \"/tmp/ansible_cloud.terraform.t
erraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/terraform_commands.py\", line 215, in show\n
  File \"/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/model
s.py\", line 108, in from_json\n  File \"/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terr
aform/plugins/module_utils/models.py\", line 93, in from_json\n  File \"/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip
/ansible_collections/cloud/terraform/plugins/module_utils/models.py\", line 78, in from_json\n  File \"/tmp/ansible_cloud.terraform.terraform_payload_dc9y5y_0/ansible_cloud.
terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/models.py\", line 78, in <listcomp>\n  File \"/tmp/ansible_cloud.terraform.terraform
_payload_dc9y5y_0/ansible_cloud.terraform.terraform_payload.zip/ansible_collections/cloud/terraform/plugins/module_utils/models.py\", line 49, in from_json\nKeyError: 'value
s'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by gravesm** [comment]
For some reason there's a field missing from the `aws_sqs_queue_policy` resource in the `terraform show` output, which is causing this failure. The module will probably need to have some checks in place to account for this.

**Comment by jce-redhat** [comment]
I think the issue is the `aws_sqs_queue_policy` only takes two arguments, both of which need to be calculated so there are no default or defined values:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_policy

Because of this, the plan file that gets created has an entry for the `aws_sqs_queue_policy` resource, but the "values" dictionary key is completely absent.  I haven't found another resource like this to test against, but for other resources where there are default argument values, those values get populated in the plan even if they are not defined in the actual .tf file.
